CREATE TABLE `FUNKCIA` (
  `ID` INT NOT NULL,
  `NAZOV` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`));

  CREATE TABLE `OSOBA` (
  `ID` INT NOT NULL,
  `NAZOV` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FUNKCIA`
    FOREIGN KEY (`ID`)
    REFERENCES `FUNKCIA` (`ID`));

	CREATE TABLE `EPARCHIA` (
  `ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `EPARCHY`
    FOREIGN KEY (`ID`)
    REFERENCES `OSOBA` (`ID`));

CREATE TABLE `PROTOPRESBYTERAT` (
  `ID` INT NOT NULL,
  `NAZOV` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `EPARCHIA`
    FOREIGN KEY (`ID`)
    REFERENCES `EPARCHIA` (`ID`),
  CONSTRAINT `PROTOPRESBYTER`
    FOREIGN KEY (`ID`)
    REFERENCES `OSOBA` (`ID`));

CREATE TABLE `FARNOST` (
  `ID` INT NOT NULL,
  `NAZOV` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `PROTOPRESBYTERAT`
    FOREIGN KEY (`ID`)
    REFERENCES `PROTOPRESBYTERAT` (`id`),
  CONSTRAINT `SPRAVCA`
    FOREIGN KEY (`ID`)
    REFERENCES `OSOBA` (`ID`));

CREATE TABLE `KAPLAN` (
  `ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `OSOBA`
    FOREIGN KEY (`ID`)
    REFERENCES `OSOBA` (`ID`),
  CONSTRAINT `FARNOST`
    FOREIGN KEY (`ID`)
    REFERENCES `FARNOST` (`ID`));

CREATE TABLE `VYPOMOCNYDUCHOVNY` (
  `ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `MENO`
    FOREIGN KEY (`ID`)
    REFERENCES `OSOBA` (`ID`),
  CONSTRAINT `PARISH`
    FOREIGN KEY (`ID`)
    REFERENCES `FARNOST` (`id`));

CREATE TABLE `FILIALKA` (
  `ID` INT NOT NULL,
  `NAZOV` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `MPARISH`
    FOREIGN KEY (`ID`)
    REFERENCES `FARNOST` (`ID`));